### ISSUE TITLE
Columns "Routes Received" and "Filtered" show the same values

### ISSUE THREAD

**Issue by Brueggus** [alice-lg/alice-lg#69] opened 2021-05-22 19:11 UTC
We've updated alice-lg and birdwatcher to their current versions today. Now both columns "Received" + "Filtered" show the same values although in most cases all routes are accepted or only some of them are filtered.

![image](https://user-images.githubusercontent.com/37619/119238300-06b9af00-bb42-11eb-9dd2-4a319c51bbe4.png)

We're running BIRD 1. Is there any configuration parameter I may be missing?

On the details page for the respective ASes, the routes are shown correctly as filtered / accepted.

![image](https://user-images.githubusercontent.com/37619/119238535-230a1b80-bb43-11eb-83cd-1a6ecd897247.png)

**Comment by bluikko** [comment] 2021-06-29 14:27
I saw this issue when I changed the `type` configuration parameter to `multi_table`. Setting it to `single_table` shows those numbers right (can't get IPv6 to show more than 0, though).

The setup here is BIRD2 with only `master4` and `master6` tables.

**Comment by annikahannig** [comment] 2021-07-05 16:03
I'll check if I can reproduce this.

Is the `birdwatcher` up to date? :)

**Comment by Brueggus** [comment] 2021-07-05 20:12
> I saw this issue when I changed the `type` configuration parameter to `multi_table`. Setting it to `single_table` shows those numbers right

Thanks @bluikko - this did the trick for us! I'll leave this one open so we can work on your issue with IPv6.

**Comment by annikahannig** [comment] 2022-11-17 11:06
Looks like this was a config issue. I'll close this.

**Closed by annikahannig** 2022-11-17 11:06 UTC
